// Copyright (c) 2025 Bytedance Ltd. and/or its affiliates
// Licensed under the 【火山方舟】原型应用软件自用许可协议
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at 
//     https://www.volcengine.com/docs/82379/1433703
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

import * as dataset from './namespaces/dataset';
import * as dialog from './namespaces/dialog';
import * as model from './namespaces/model';
import * as optimization from './namespaces/optimization';
import * as prompt from './namespaces/prompt';
import * as schema from './namespaces/schema';
import * as task from './namespaces/task';
import * as user_info from './namespaces/user_info';

export { dataset, dialog, model, optimization, prompt, schema, task, user_info };

export default class AutopeService<T> {
  private request: any = () => {
    throw new Error('AutopeService.request is undefined');
  };
  private baseURL: string | ((path: string) => string) = '';

  constructor(options?: {
    baseURL?: string | ((path: string) => string);
    request?<R>(
      params: {
        url: string;
        method: 'GET' | 'DELETE' | 'POST' | 'PUT' | 'PATCH';
        data?: any;
        params?: any;
        headers?: any;
      },
      options?: T,
    ): Promise<R>;
  }) {
    this.request = options?.request || this.request;
    this.baseURL = options?.baseURL || '';
  }

  private genBaseURL(path: string) {
    return typeof this.baseURL === 'string' ? this.baseURL + path : this.baseURL(path);
  }

  /** POST /open/UpdateAutoPETask */
  UpdateAutoPETask(req: task.UpdateAutoPETaskReq, options?: T): Promise<task.UpdateAutoPETaskResp> {
    const _req = req;
    const url = this.genBaseURL('/open/UpdateAutoPETask');
    const method = 'POST';
    const data = {
      TaskId: _req['TaskId'],
      TaskName: _req['TaskName'],
      Prompt: _req['Prompt'],
      LastVersion: _req['LastVersion'],
    };
    return this.request({ url, method, data }, options);
  }

  /** POST /open/ListAutoPETasks */
  ListAutoPETasks(req?: task.ListAutoPETasksReq, options?: T): Promise<task.ListAutoPETasksResp> {
    const _req = req || {};
    const url = this.genBaseURL('/open/ListAutoPETasks');
    const method = 'POST';
    const data = {
      Filter: _req['Filter'],
      Limit: _req['Limit'],
      Offset: _req['Offset'],
      SortBy: _req['SortBy'],
      ProjectName: _req['ProjectName'],
      TagFilters: _req['TagFilters'],
    };
    return this.request({ url, method, data }, options);
  }

  /**
   * POST /open/CreateAutoPETask
   *
   * List tasks method
   */
  CreateAutoPETask(req: task.CreateAutoPETaskReq, options?: T): Promise<task.CreateAutoPETaskResp> {
    const _req = req;
    const url = this.genBaseURL('/open/CreateAutoPETask');
    const method = 'POST';
    const data = {
      TaskName: _req['TaskName'],
      TaskType: _req['TaskType'],
      Prompt: _req['Prompt'],
      TargetModel: _req['TargetModel'],
      Temperature: _req['Temperature'],
      TopP: _req['TopP'],
      ProjectName: _req['ProjectName'],
      Tags: _req['Tags'],
      ScoreType: _req['ScoreType'],
      FromAgent: _req['FromAgent'],
    };
    return this.request({ url, method, data }, options);
  }

  /** POST /open/DeleteAutoPETask */
  DeleteAutoPETask(req: task.DeleteAutoPETaskReq, options?: T): Promise<task.DeleteAutoPETaskResp> {
    const _req = req;
    const url = this.genBaseURL('/open/DeleteAutoPETask');
    const method = 'POST';
    const data = { TaskId: _req['TaskId'] };
    return this.request({ url, method, data }, options);
  }

  /** POST /open/ListAutoPEDataRecords */
  ListAutoPEDataRecords(
    req: dataset.ListAutoPEDataRecordsReq,
    options?: T,
  ): Promise<dataset.ListAutoPEDataRecordsResp> {
    const _req = req;
    const url = this.genBaseURL('/open/ListAutoPEDataRecords');
    const method = 'POST';
    const data = {
      TaskId: _req['TaskId'],
      PromptVersionId: _req['PromptVersionId'],
      Limit: _req['Limit'],
      Offset: _req['Offset'],
      ComparePromptVersionId: _req['ComparePromptVersionId'],
      Filter: _req['Filter'],
    };
    return this.request({ url, method, data }, options);
  }

  /** POST /open/BatchCreateAutoPEDataRecords */
  BatchCreateAutoPEDataRecords(
    req: dataset.BatchCreateAutoPEDataRecordsReq,
    options?: T,
  ): Promise<dataset.BatchCreateAutoPEDataRecordsResp> {
    const _req = req;
    const url = this.genBaseURL('/open/BatchCreateAutoPEDataRecords');
    const method = 'POST';
    const data = { TaskId: _req['TaskId'], PromptVersionId: _req['PromptVersionId'], Records: _req['Records'] };
    return this.request({ url, method, data }, options);
  }

  /** POST /open/GetAutoPEEvaluateDimensionHistory */
  GetAutoPEEvaluateDimensionHistory(
    req: task.GetAutoPEEvaluateDimensionHistoryReq,
    options?: T,
  ): Promise<task.GetAutoPEEvaluateDimensionHistoryResp> {
    const _req = req;
    const url = this.genBaseURL('/open/GetAutoPEEvaluateDimensionHistory');
    const method = 'POST';
    const data = { TaskId: _req['TaskId'] };
    return this.request({ url, method, data }, options);
  }

  /**
   * POST /open/ListAvailableModels
   *
   * Model info
   */
  ListAvailableModels(req?: schema.Empty, options?: T): Promise<model.ListAvailableModelsResp> {
    const url = this.genBaseURL('/open/ListAvailableModels');
    const method = 'POST';
    return this.request({ url, method }, options);
  }

  /** POST /open/UpdateAutoPEDataRecord */
  UpdateAutoPEDataRecord(
    req: dataset.UpdateAutoPEDataRecordReq,
    options?: T,
  ): Promise<dataset.UpdateAutoPEDataRecordResp> {
    const _req = req;
    const url = this.genBaseURL('/open/UpdateAutoPEDataRecord');
    const method = 'POST';
    const data = {
      TaskId: _req['TaskId'],
      PromptVersionId: _req['PromptVersionId'],
      RecordId: _req['RecordId'],
      VariablesValues: _req['VariablesValues'],
      ReferenceAnswer: _req['ReferenceAnswer'],
      UserScore: _req['UserScore'],
      UserAnalysis: _req['UserAnalysis'],
      CompletionText: _req['CompletionText'],
      EvalModelScore: _req['EvalModelScore'],
      EvalModelAnalysis: _req['EvalModelAnalysis'],
      GSBResult: _req['GSBResult'],
    };
    return this.request({ url, method, data }, options);
  }

  /** POST /open/LatestJobProgress */
  LatestJobProgress(req: dataset.LatestJobProgressReq, options?: T): Promise<dataset.LatestJobProgressResp> {
    const _req = req;
    const url = this.genBaseURL('/open/LatestJobProgress');
    const method = 'POST';
    const data = { TaskId: _req['TaskId'], PromptVersionIds: _req['PromptVersionIds'] };
    return this.request({ url, method, data }, options);
  }

  /** POST /open/CancelOptimize */
  CancelOptimize(req: optimization.CancelOptimizeReq, options?: T): Promise<optimization.CancelOptimizeResp> {
    const _req = req;
    const url = this.genBaseURL('/open/CancelOptimize');
    const method = 'POST';
    const data = { TaskId: _req['TaskId'], PromptVersionId: _req['PromptVersionId'] };
    return this.request({ url, method, data }, options);
  }

  /** POST /open/RunOptimize */
  RunOptimize(req: optimization.RunOptimizeReq, options?: T): Promise<optimization.RunOptimizeResp> {
    const _req = req;
    const url = this.genBaseURL('/open/RunOptimize');
    const method = 'POST';
    const data = {
      TaskId: _req['TaskId'],
      PromptVersionId: _req['PromptVersionId'],
      OptimizeEvaluateDimension: _req['OptimizeEvaluateDimension'],
      StopConfig: _req['StopConfig'],
      OptimizeModeRate: _req['OptimizeModeRate'],
    };
    return this.request({ url, method, data }, options);
  }

  /** POST /open/ListAutoPEPromptVersion */
  ListAutoPEPromptVersion(
    req: prompt.ListAutoPEPromptVersionReq,
    options?: T,
  ): Promise<prompt.ListAutoPEPromptVersionResp> {
    const _req = req;
    const url = this.genBaseURL('/open/ListAutoPEPromptVersion');
    const method = 'POST';
    const data = {
      TaskId: _req['TaskId'],
      BaselinePromptVersionId: _req['BaselinePromptVersionId'],
      Filter: _req['Filter'],
      FindPredecessor: _req['FindPredecessor'],
    };
    return this.request({ url, method, data }, options);
  }

  /**
   * POST /open/GetExamplePromptList
   *
   * Generate prompt method with streaming responses
   */
  GetExamplePromptList(req?: schema.Empty, options?: T): Promise<prompt.GetExamplePromptListResp> {
    const url = this.genBaseURL('/open/GetExamplePromptList');
    const method = 'POST';
    return this.request({ url, method }, options);
  }

  /** POST /open/GeneratePrompt */
  GeneratePrompt(req: prompt.GeneratePromptReq, options?: T): Promise<Array<prompt.GeneratePromptEventResp>> {
    const _req = req;
    const url = this.genBaseURL('/open/GeneratePrompt');
    const method = 'POST';
    const data = {
      TaskId: _req['TaskId'],
      Rule: _req['Rule'],
      ProjectName: _req['ProjectName'],
      ModelName: _req['ModelName'],
      Temperature: _req['Temperature'],
      TopP: _req['TopP'],
      Feedback: _req['Feedback'],
      CurrentPrompt: _req['CurrentPrompt'],
    };
    return this.request({ url, method, data }, options);
  }

  /** POST /open/EvaluateAutoPEDataRecord */
  EvaluateAutoPEDataRecord(
    req: dataset.EvaluateAutoPEDataRecordReq,
    options?: T,
  ): Promise<dataset.EvaluateAutoPEDataRecordResp> {
    const _req = req;
    const url = this.genBaseURL('/open/EvaluateAutoPEDataRecord');
    const method = 'POST';
    const data = {
      TaskId: _req['TaskId'],
      PromptVersionId: _req['PromptVersionId'],
      DataRecordId: _req['DataRecordId'],
    };
    return this.request({ url, method, data }, options);
  }

  /** POST /open/BatchEvaluate */
  BatchEvaluate(req: dataset.BatchEvaluateReq, options?: T): Promise<dataset.BatchEvaluateResp> {
    const _req = req;
    const url = this.genBaseURL('/open/BatchEvaluate');
    const method = 'POST';
    const data = {
      TaskId: _req['TaskId'],
      PromptVersionIds: _req['PromptVersionIds'],
      EvaluateAll: _req['EvaluateAll'],
      DataRecordIds: _req['DataRecordIds'],
    };
    return this.request({ url, method, data }, options);
  }

  /**
   * POST /open/CompareOptimizationResult
   *
   * Optimization
   */
  CompareOptimizationResult(
    req: optimization.CompareOptimizationResultReq,
    options?: T,
  ): Promise<optimization.CompareOptimizationResultResp> {
    const _req = req;
    const url = this.genBaseURL('/open/CompareOptimizationResult');
    const method = 'POST';
    const data = {
      TaskId: _req['TaskId'],
      BasePromptVersionId: _req['BasePromptVersionId'],
      ComparePromptVersionId: _req['ComparePromptVersionId'],
    };
    return this.request({ url, method, data }, options);
  }

  /** POST /open/UpdateAutoPEPromptVersion */
  UpdateAutoPEPromptVersion(
    req: prompt.UpdateAutoPEPromptVersionReq,
    options?: T,
  ): Promise<prompt.UpdateAutoPEPromptVersionResp> {
    const _req = req;
    const url = this.genBaseURL('/open/UpdateAutoPEPromptVersion');
    const method = 'POST';
    const data = {
      TaskId: _req['TaskId'],
      PromptVersionId: _req['PromptVersionId'],
      Messages: _req['Messages'],
      Variables: _req['Variables'],
      ModelName: _req['ModelName'],
      TopP: _req['TopP'],
      Temperature: _req['Temperature'],
      EvaluationDimension: _req['EvaluationDimension'],
      GenerateEvaluateDimension: _req['GenerateEvaluateDimension'],
      Feedbacks: _req['Feedbacks'],
      VoteType: _req['VoteType'],
      ModifyMessageIdx: _req['ModifyMessageIdx'],
      RefAnswerModelSpec: _req['RefAnswerModelSpec'],
      ReferenceDialogMessages: _req['ReferenceDialogMessages'],
    };
    return this.request({ url, method, data }, options);
  }

  /** POST /open/GetAutoPEPromptVersion */
  GetAutoPEPromptVersion(
    req: prompt.GetAutoPEPromptVersionReq,
    options?: T,
  ): Promise<prompt.GetAutoPEPromptVersionResp> {
    const _req = req;
    const url = this.genBaseURL('/open/GetAutoPEPromptVersion');
    const method = 'POST';
    const data = { TaskId: _req['TaskId'], VersionId: _req['VersionId'], Latest: _req['Latest'] };
    return this.request({ url, method, data }, options);
  }

  /**
   * POST /open/CreateAutoPEDataRecord
   *
   * Evaluation dataset
   */
  CreateAutoPEDataRecord(
    req: dataset.CreateAutoPEDataRecordReq,
    options?: T,
  ): Promise<dataset.CreateAutoPEDataRecordResp> {
    const _req = req;
    const url = this.genBaseURL('/open/CreateAutoPEDataRecord');
    const method = 'POST';
    const data = {
      TaskId: _req['TaskId'],
      PromptVersionId: _req['PromptVersionId'],
      VariablesValues: _req['VariablesValues'],
      ModelAnswer: _req['ModelAnswer'],
      ReferenceAnswer: _req['ReferenceAnswer'],
      UserScore: _req['UserScore'],
      UserAnalysis: _req['UserAnalysis'],
      GSBResult: _req['GSBResult'],
    };
    return this.request({ url, method, data }, options);
  }

  /** POST /open/BatchCompletion */
  BatchCompletion(req: dataset.BatchCompletionReq, options?: T): Promise<dataset.BatchCompletionResp> {
    const _req = req;
    const url = this.genBaseURL('/open/BatchCompletion');
    const method = 'POST';
    const data = {
      TaskId: _req['TaskId'],
      PromptVersionIds: _req['PromptVersionIds'],
      DataRecordIds: _req['DataRecordIds'],
      CompletionContent: _req['CompletionContent'],
    };
    return this.request({ url, method, data }, options);
  }

  /** POST /open/GenerateVariablesValues */
  GenerateVariablesValues(
    req: prompt.GenerateVariablesValuesReq,
    options?: T,
  ): Promise<Array<prompt.GenerateVariablesValuesEventResp>> {
    const _req = req;
    const url = this.genBaseURL('/open/GenerateVariablesValues');
    const method = 'POST';
    const data = {
      TaskId: _req['TaskId'],
      Messages: _req['Messages'],
      GenerationLogic: _req['GenerationLogic'],
      PromptVersionId: _req['PromptVersionId'],
      ModelName: _req['ModelName'],
      Temperature: _req['Temperature'],
      TopP: _req['TopP'],
      UseInternetSearch: _req['UseInternetSearch'],
    };
    return this.request({ url, method, data }, options);
  }

  /** POST /open/BatchGenerateVariabesValues */
  BatchGenerateVariabesValues(
    req: dataset.BatchGenerateVariabesValuesReq,
    options?: T,
  ): Promise<dataset.BatchGenerateVariabesValuesResp> {
    const _req = req;
    const url = this.genBaseURL('/open/BatchGenerateVariabesValues');
    const method = 'POST';
    const data = {
      TaskId: _req['TaskId'],
      PromptVersionIds: _req['PromptVersionIds'],
      GenerationLogic: _req['GenerationLogic'],
      TotalGenerateCasesNumber: _req['TotalGenerateCasesNumber'],
    };
    return this.request({ url, method, data }, options);
  }

  /** POST /open/CreateAutoPEEvaluateDimension */
  CreateAutoPEEvaluateDimension(
    req: task.CreateAutoPEEvaluateDimensionReq,
    options?: T,
  ): Promise<task.CreateAutoPEEvaluateDimensionResp> {
    const _req = req;
    const url = this.genBaseURL('/open/CreateAutoPEEvaluateDimension');
    const method = 'POST';
    const data = { TaskId: _req['TaskId'], PromptVersionId: _req['PromptVersionId'], Content: _req['Content'] };
    return this.request({ url, method, data }, options);
  }

  /** POST /open/Completion */
  Completion(req: prompt.CompletionReq, options?: T): Promise<Array<prompt.CompletionEventResp>> {
    const _req = req;
    const url = this.genBaseURL('/open/Completion');
    const method = 'POST';
    const data = {
      TaskId: _req['TaskId'],
      ModelName: _req['ModelName'],
      PromptVersionId: _req['PromptVersionId'],
      Variables: _req['Variables'],
      Temperature: _req['Temperature'],
      TopP: _req['TopP'],
      Messages: _req['Messages'],
      CompletingDialog: _req['CompletingDialog'],
    };
    return this.request({ url, method, data }, options);
  }

  /**
   * POST /open/CreateAutoPEPromptVersion
   *
   * PromptVersion info
   */
  CreateAutoPEPromptVersion(
    req: prompt.CreateAutoPEPromptVersionReq,
    options?: T,
  ): Promise<prompt.CreateAutoPEPromptVersionResp> {
    const _req = req;
    const url = this.genBaseURL('/open/CreateAutoPEPromptVersion');
    const method = 'POST';
    const data = {
      TaskId: _req['TaskId'],
      ModelName: _req['ModelName'],
      BasePromptVersionId: _req['BasePromptVersionId'],
      Version: _req['Version'],
      Variables: _req['Variables'],
      TopP: _req['TopP'],
      Temperature: _req['Temperature'],
      Messages: _req['Messages'],
      SystemPrompt: _req['SystemPrompt'],
      EvaluationDimension: _req['EvaluationDimension'],
      RefAnswerModelSpec: _req['RefAnswerModelSpec'],
      ReferenceDialogMessages: _req['ReferenceDialogMessages'],
    };
    return this.request({ url, method, data }, options);
  }

  /** POST /open/DeleteAutoPEDataRecords */
  DeleteAutoPEDataRecords(
    req: dataset.DeleteAutoPEDataRecordsReq,
    options?: T,
  ): Promise<dataset.DeleteAutoPEDataRecordsResp> {
    const _req = req;
    const url = this.genBaseURL('/open/DeleteAutoPEDataRecords');
    const method = 'POST';
    const data = {
      TaskId: _req['TaskId'],
      PromptVersionIds: _req['PromptVersionIds'],
      DataRecordIds: _req['DataRecordIds'],
    };
    return this.request({ url, method, data }, options);
  }

  /**
   * POST /open/CreateAutoPEUserAgreementRecord
   *
   * User Info
   */
  CreateAutoPEUserAgreementRecord(
    req?: user_info.CreateAutoPEUserAgreementRecord,
    options?: T,
  ): Promise<user_info.CreateAutoPEUserAgreementRecordResp> {
    const _req = req || {};
    const url = this.genBaseURL('/open/CreateAutoPEUserAgreementRecord');
    const method = 'POST';
    const data = { ProjectName: _req['ProjectName'] };
    return this.request({ url, method, data }, options);
  }

  /** POST /open/GetAutoPEUserSignedAgreementInfos */
  GetAutoPEUserSignedAgreementInfos(
    req?: user_info.GetAutoPEUserSignedAgreementInfosReq,
    options?: T,
  ): Promise<user_info.GetAutoPEUserSignedAgreementInfosResp> {
    const _req = req || {};
    const url = this.genBaseURL('/open/GetAutoPEUserSignedAgreementInfos');
    const method = 'POST';
    const data = { ProjectName: _req['ProjectName'] };
    return this.request({ url, method, data }, options);
  }

  /** POST /open/GenerateAIEdition */
  GenerateAIEdition(req: prompt.GenerateAIEditionReq, options?: T): Promise<Array<prompt.GenerateAIEditionEventResp>> {
    const _req = req;
    const url = this.genBaseURL('/open/GenerateAIEdition');
    const method = 'POST';
    const data = {
      TaskId: _req['TaskId'],
      PromptVersionId: _req['PromptVersionId'],
      DataRecordId: _req['DataRecordId'],
      ContentFeedBack: _req['ContentFeedBack'],
      ModelName: _req['ModelName'],
      Temperature: _req['Temperature'],
      TopP: _req['TopP'],
    };
    return this.request({ url, method, data }, options);
  }

  /** POST /open/SaveFeedback */
  SaveFeedback(req: prompt.SaveFeedbackReq, options?: T): Promise<prompt.SaveFeedbackResp> {
    const _req = req;
    const url = this.genBaseURL('/open/SaveFeedback');
    const method = 'POST';
    const data = {
      TaskId: _req['TaskId'],
      PromptVersionId: _req['PromptVersionId'],
      DataRecordId: _req['DataRecordId'],
      ContentFeedbacks: _req['ContentFeedbacks'],
    };
    return this.request({ url, method, data }, options);
  }

  /** POST /open/GenerateAutoPEEvaluateDimension */
  GenerateAutoPEEvaluateDimension(
    req: task.GenerateAutoPEEvaluateDimensionRequest,
    options?: T,
  ): Promise<task.GenerateAutoPEEvaluateDimensionResponse> {
    const _req = req;
    const url = this.genBaseURL('/open/GenerateAutoPEEvaluateDimension');
    const method = 'POST';
    const data = { TaskId: _req['TaskId'], PromptVersionId: _req['PromptVersionId'] };
    return this.request({ url, method, data }, options);
  }

  /** POST /open/GetRandomCachedPrompt */
  GetRandomCachedPrompt(req?: schema.Empty, options?: T): Promise<prompt.GetRandomCachedPromptResp> {
    const url = this.genBaseURL('/open/GetRandomCachedPrompt');
    const method = 'POST';
    return this.request({ url, method }, options);
  }

  /** POST /open/GetMoreModelAnswer */
  GetMoreModelAnswer(req: prompt.GetMoreModelAnswerReq, options?: T): Promise<prompt.GetMoreModelAnswerResp> {
    const _req = req;
    const url = this.genBaseURL('/open/GetMoreModelAnswer');
    const method = 'POST';
    const data = { TaskId: _req['TaskId'], PromptVersionId: _req['PromptVersionId'] };
    return this.request({ url, method, data }, options);
  }

  /** POST /open/GenerateMoreModelAnswer */
  GenerateMoreModelAnswer(
    req: prompt.GenerateMoreModelAnswerReq,
    options?: T,
  ): Promise<prompt.GenerateMoreModelAnswerResp> {
    const _req = req;
    const url = this.genBaseURL('/open/GenerateMoreModelAnswer');
    const method = 'POST';
    const data = {
      TaskId: _req['TaskId'],
      PromptVersionId: _req['PromptVersionId'],
      ModelName: _req['ModelName'],
      Temperature: _req['Temperature'],
      TopP: _req['TopP'],
      Messages: _req['Messages'],
    };
    return this.request({ url, method, data }, options);
  }

  /** POST /open/GetAutoPETaskIntentions */
  GetAutoPETaskIntentions(
    req: prompt.GetAutoPETaskIntentionsReq,
    options?: T,
  ): Promise<prompt.GetAutoPETaskIntentionsResp> {
    const _req = req;
    const url = this.genBaseURL('/open/GetAutoPETaskIntentions');
    const method = 'POST';
    const data = { TaskId: _req['TaskId'] };
    return this.request({ url, method, data }, options);
  }

  /** POST /open/GenerateIdealAnswer */
  GenerateIdealAnswer(
    req: prompt.GenerateIdealAnswerReq,
    options?: T,
  ): Promise<Array<prompt.GenerateIdealAnswerEventResp>> {
    const _req = req;
    const url = this.genBaseURL('/open/GenerateIdealAnswer');
    const method = 'POST';
    const data = {
      TaskId: _req['TaskId'],
      PromptVersionId: _req['PromptVersionId'],
      ModelName: _req['ModelName'],
      Temperature: _req['Temperature'],
      Variables: _req['Variables'],
      TopP: _req['TopP'],
      OriginAnswer: _req['OriginAnswer'],
      Feedback: _req['Feedback'],
    };
    return this.request({ url, method, data }, options);
  }

  /** POST /open/DeleteAutoPETaskIntentions */
  DeleteAutoPETaskIntentions(
    req: prompt.DeleteAutoPETaskIntentionsReq,
    options?: T,
  ): Promise<prompt.DeleteAutoPETaskIntentionsResp> {
    const _req = req;
    const url = this.genBaseURL('/open/DeleteAutoPETaskIntentions');
    const method = 'POST';
    const data = { TaskId: _req['TaskId'], IntentionIds: _req['IntentionIds'] };
    return this.request({ url, method, data }, options);
  }

  /** POST /open/CreateAutoPETaskIntentions */
  CreateAutoPETaskIntentions(
    req: prompt.CreateAutoPETaskIntentionsReq,
    options?: T,
  ): Promise<prompt.CreateAutoPETaskIntentionsResp> {
    const _req = req;
    const url = this.genBaseURL('/open/CreateAutoPETaskIntentions');
    const method = 'POST';
    const data = { TaskId: _req['TaskId'], VariablesValues: _req['VariablesValues'] };
    return this.request({ url, method, data }, options);
  }

  /** POST /open/GetAutoPETaskTokenConsumption */
  GetAutoPETaskTokenConsumption(
    req: task.GetAutoPETaskTokenConsumptionReq,
    options?: T,
  ): Promise<task.GetAutoPETaskTokenConsumptionResp> {
    const _req = req;
    const url = this.genBaseURL('/open/GetAutoPETaskTokenConsumption');
    const method = 'POST';
    const data = { TaskId: _req['TaskId'] };
    return this.request({ url, method, data }, options);
  }

  /** POST /open/UpdateAutoPEDialogRecord */
  UpdateAutoPEDialogRecord(
    req: dialog.UpdateAutoPEDialogRecordReq,
    options?: T,
  ): Promise<dialog.UpdateAutoPEDialogRecordResp> {
    const _req = req;
    const url = this.genBaseURL('/open/UpdateAutoPEDialogRecord');
    const method = 'POST';
    const data = {
      TaskId: _req['TaskId'],
      PromptVersionId: _req['PromptVersionId'],
      DialogId: _req['DialogId'],
      Messages: _req['Messages'],
      Feedbacks: _req['Feedbacks'],
      Score: _req['Score'],
      Attributes: _req['Attributes'],
      Analysis: _req['Analysis'],
      ModifyMessageIdx: _req['ModifyMessageIdx'],
    };
    return this.request({ url, method, data }, options);
  }

  /** POST /open/DeleteAutoPEDialogRecord */
  DeleteAutoPEDialogRecord(
    req: dialog.DeleteAutoPEDialogRecordReq,
    options?: T,
  ): Promise<dialog.DeleteAutoPEDialogRecordResp> {
    const _req = req;
    const url = this.genBaseURL('/open/DeleteAutoPEDialogRecord');
    const method = 'POST';
    const data = { TaskId: _req['TaskId'], DialogIds: _req['DialogIds'], PromptVersionId: _req['PromptVersionId'] };
    return this.request({ url, method, data }, options);
  }

  /** POST /open/CreateAutoPEDialogRecord */
  CreateAutoPEDialogRecord(
    req: dialog.CreateAutoPEDialogRecordReq,
    options?: T,
  ): Promise<dialog.CreateAutoPEDialogRecordResp> {
    const _req = req;
    const url = this.genBaseURL('/open/CreateAutoPEDialogRecord');
    const method = 'POST';
    const data = {
      TaskId: _req['TaskId'],
      PromptVersionId: _req['PromptVersionId'],
      Messages: _req['Messages'],
      Feedbacks: _req['Feedbacks'],
      Score: _req['Score'],
      Attributes: _req['Attributes'],
    };
    return this.request({ url, method, data }, options);
  }

  /** POST /open/GetAutoPEDialogRecord */
  GetAutoPEDialogRecord(req: dialog.GetAutoPEDialogRecordReq, options?: T): Promise<dialog.GetAutoPEDialogRecordResp> {
    const _req = req;
    const url = this.genBaseURL('/open/GetAutoPEDialogRecord');
    const method = 'POST';
    const data = { TaskId: _req['TaskId'], DialogId: _req['DialogId'] };
    return this.request({ url, method, data }, options);
  }

  /** POST /open/ListAutoPEDialogRecords */
  ListAutoPEDialogRecords(
    req: dialog.ListAutoPEDialogRecordsReq,
    options?: T,
  ): Promise<dialog.ListAutoPEDialogRecordsResp> {
    const _req = req;
    const url = this.genBaseURL('/open/ListAutoPEDialogRecords');
    const method = 'POST';
    const data = {
      TaskId: _req['TaskId'],
      PromptVersionIds: _req['PromptVersionIds'],
      DialogIds: _req['DialogIds'],
      Filter: _req['Filter'],
      Limit: _req['Limit'],
      Offset: _req['Offset'],
    };
    return this.request({ url, method, data }, options);
  }

  /**
   * POST /open/GetAutoPEDialogExamples
   *
   * Dialog
   */
  GetAutoPEDialogExamples(req?: schema.Empty, options?: T): Promise<dialog.GetAutoPEDialogExamplesResp> {
    const url = this.genBaseURL('/open/GetAutoPEDialogExamples');
    const method = 'POST';
    return this.request({ url, method }, options);
  }

  /** POST /open/BatchCreateAutoPEDialogRecords */
  BatchCreateAutoPEDialogRecords(
    req: dialog.BatchCreateAutoPEDialogRecordsReq,
    options?: T,
  ): Promise<dialog.BatchCreateAutoPEDialogRecordsResp> {
    const _req = req;
    const url = this.genBaseURL('/open/BatchCreateAutoPEDialogRecords');
    const method = 'POST';
    const data = { TaskId: _req['TaskId'], PromptVersionId: _req['PromptVersionId'], Dialogs: _req['Dialogs'] };
    return this.request({ url, method, data }, options);
  }

  /** POST /open/GenerateTunedPromptFromFeedback */
  GenerateTunedPromptFromFeedback(
    req: dialog.GenerateTunedPromptFromFeedbackReq,
    options?: T,
  ): Promise<Array<dialog.GenerateTunedPromptFromFeedbackEventResp>> {
    const _req = req;
    const url = this.genBaseURL('/open/GenerateTunedPromptFromFeedback');
    const method = 'POST';
    const data = { TaskId: _req['TaskId'], PromptVersionId: _req['PromptVersionId'], Feedback: _req['Feedback'] };
    return this.request({ url, method, data }, options);
  }

  /** POST /open/GenerateTunedPromptFromGSBFeedback */
  GenerateTunedPromptFromGSBFeedback(
    req: prompt.GenerateTunedPromptFromGSBFeedbackReq,
    options?: T,
  ): Promise<Array<prompt.GenerateTunedPromptFromGSBFeedbackResp>> {
    const _req = req;
    const url = this.genBaseURL('/open/GenerateTunedPromptFromGSBFeedback');
    const method = 'POST';
    const data = {
      TaskId: _req['TaskId'],
      PromptVersionId: _req['PromptVersionId'],
      ModelAnswer: _req['ModelAnswer'],
      RefAnswer: _req['RefAnswer'],
      GSBResult: _req['GSBResult'],
      UserAnalysis: _req['UserAnalysis'],
    };
    return this.request({ url, method, data }, options);
  }

  /** POST /open/GetAutoPETask */
  GetAutoPETask(req: task.GetAutoPETaskReq, options?: T): Promise<task.GetAutoPETaskResp> {
    const _req = req;
    const url = this.genBaseURL('/open/GetAutoPETask');
    const method = 'POST';
    const data = { TaskId: _req['TaskId'], ProjectName: _req['ProjectName'] };
    return this.request({ url, method, data }, options);
  }

  /** POST /open/RunAgentOnlineOptimize */
  RunAgentOnlineOptimize(
    req: optimization.RunAgentOnlineOptimizeReq,
    options?: T,
  ): Promise<optimization.RunAgentOnlineOptimizeResp> {
    const _req = req;
    const url = this.genBaseURL('/open/RunAgentOnlineOptimize');
    const method = 'POST';
    const data = { ProjectName: _req['ProjectName'] };
    return this.request({ url, method, data }, options);
  }

  /**
   * POST /open/CreateAutoPEAgentDataRecord
   *
   * agent optimize
   */
  CreateAutoPEAgentDataRecord(
    req: dataset.CreateAutoPEAgentDataRecordReq,
    options?: T,
  ): Promise<dataset.CreateAutoPEAgentDataRecordResp> {
    const _req = req;
    const url = this.genBaseURL('/open/CreateAutoPEAgentDataRecord');
    const method = 'POST';
    const data = {
      ProjectName: _req['ProjectName'],
      SessionId: _req['SessionId'],
      WorkflowStepMessages: _req['WorkflowStepMessages'],
      Feedback: _req['Feedback'],
      TenantAccountId: _req['TenantAccountId'],
      TenantUserId: _req['TenantUserId'],
    };
    return this.request({ url, method, data }, options);
  }

  /** POST /open/UpdateAutoPEAgentPromptTemplate */
  UpdateAutoPEAgentPromptTemplate(
    req: prompt.UpdateAutoPEAgentPromptTemplateReq,
    options?: T,
  ): Promise<prompt.UpdateAutoPEAgentPromptTemplateResp> {
    const _req = req;
    const url = this.genBaseURL('/open/UpdateAutoPEAgentPromptTemplate');
    const method = 'POST';
    const data = { AutoPEProjectId: _req['AutoPEProjectId'], StepIndex: _req['StepIndex'] };
    return this.request({ url, method, data }, options);
  }

  /** POST /open/GetRunAgentOnlineOptimizeResult */
  GetRunAgentOnlineOptimizeResult(
    req: optimization.GetRunAgentOnlineOptimizeResultReq,
    options?: T,
  ): Promise<optimization.GetRunAgentOnlineOptimizeResultResp> {
    const _req = req;
    const url = this.genBaseURL('/open/GetRunAgentOnlineOptimizeResult');
    const method = 'POST';
    const data = {
      ProjectName: _req['ProjectName'],
      TenantAccountId: _req['TenantAccountId'],
      TenantUserId: _req['TenantUserId'],
    };
    return this.request({ url, method, data }, options);
  }
}

export interface IAutopeService {
  /** POST /open/UpdateAutoPETask */
  UpdateAutoPETask(req: task.UpdateAutoPETaskReq): Promise<task.UpdateAutoPETaskResp>;
  /** POST /open/ListAutoPETasks */
  ListAutoPETasks(req: task.ListAutoPETasksReq): Promise<task.ListAutoPETasksResp>;
  /**
   * POST /open/CreateAutoPETask
   *
   * List tasks method
   */
  CreateAutoPETask(req: task.CreateAutoPETaskReq): Promise<task.CreateAutoPETaskResp>;
  /** POST /open/DeleteAutoPETask */
  DeleteAutoPETask(req: task.DeleteAutoPETaskReq): Promise<task.DeleteAutoPETaskResp>;
  /** POST /open/ListAutoPEDataRecords */
  ListAutoPEDataRecords(req: dataset.ListAutoPEDataRecordsReq): Promise<dataset.ListAutoPEDataRecordsResp>;
  /** POST /open/BatchCreateAutoPEDataRecords */
  BatchCreateAutoPEDataRecords(
    req: dataset.BatchCreateAutoPEDataRecordsReq,
  ): Promise<dataset.BatchCreateAutoPEDataRecordsResp>;
  /** POST /open/GetAutoPEEvaluateDimensionHistory */
  GetAutoPEEvaluateDimensionHistory(
    req: task.GetAutoPEEvaluateDimensionHistoryReq,
  ): Promise<task.GetAutoPEEvaluateDimensionHistoryResp>;
  /**
   * POST /open/ListAvailableModels
   *
   * Model info
   */
  ListAvailableModels(req: schema.Empty): Promise<model.ListAvailableModelsResp>;
  /** POST /open/UpdateAutoPEDataRecord */
  UpdateAutoPEDataRecord(req: dataset.UpdateAutoPEDataRecordReq): Promise<dataset.UpdateAutoPEDataRecordResp>;
  /** POST /open/LatestJobProgress */
  LatestJobProgress(req: dataset.LatestJobProgressReq): Promise<dataset.LatestJobProgressResp>;
  /** POST /open/CancelOptimize */
  CancelOptimize(req: optimization.CancelOptimizeReq): Promise<optimization.CancelOptimizeResp>;
  /** POST /open/RunOptimize */
  RunOptimize(req: optimization.RunOptimizeReq): Promise<optimization.RunOptimizeResp>;
  /** POST /open/ListAutoPEPromptVersion */
  ListAutoPEPromptVersion(req: prompt.ListAutoPEPromptVersionReq): Promise<prompt.ListAutoPEPromptVersionResp>;
  /**
   * POST /open/GetExamplePromptList
   *
   * Generate prompt method with streaming responses
   */
  GetExamplePromptList(req: schema.Empty): Promise<prompt.GetExamplePromptListResp>;
  /** POST /open/GeneratePrompt */
  GeneratePrompt(req: prompt.GeneratePromptReq): Promise<Array<prompt.GeneratePromptEventResp>>;
  /** POST /open/EvaluateAutoPEDataRecord */
  EvaluateAutoPEDataRecord(req: dataset.EvaluateAutoPEDataRecordReq): Promise<dataset.EvaluateAutoPEDataRecordResp>;
  /** POST /open/BatchEvaluate */
  BatchEvaluate(req: dataset.BatchEvaluateReq): Promise<dataset.BatchEvaluateResp>;
  /**
   * POST /open/CompareOptimizationResult
   *
   * Optimization
   */
  CompareOptimizationResult(
    req: optimization.CompareOptimizationResultReq,
  ): Promise<optimization.CompareOptimizationResultResp>;
  /** POST /open/UpdateAutoPEPromptVersion */
  UpdateAutoPEPromptVersion(req: prompt.UpdateAutoPEPromptVersionReq): Promise<prompt.UpdateAutoPEPromptVersionResp>;
  /** POST /open/GetAutoPEPromptVersion */
  GetAutoPEPromptVersion(req: prompt.GetAutoPEPromptVersionReq): Promise<prompt.GetAutoPEPromptVersionResp>;
  /**
   * POST /open/CreateAutoPEDataRecord
   *
   * Evaluation dataset
   */
  CreateAutoPEDataRecord(req: dataset.CreateAutoPEDataRecordReq): Promise<dataset.CreateAutoPEDataRecordResp>;
  /** POST /open/BatchCompletion */
  BatchCompletion(req: dataset.BatchCompletionReq): Promise<dataset.BatchCompletionResp>;
  /** POST /open/GenerateVariablesValues */
  GenerateVariablesValues(
    req: prompt.GenerateVariablesValuesReq,
  ): Promise<Array<prompt.GenerateVariablesValuesEventResp>>;
  /** POST /open/BatchGenerateVariabesValues */
  BatchGenerateVariabesValues(
    req: dataset.BatchGenerateVariabesValuesReq,
  ): Promise<dataset.BatchGenerateVariabesValuesResp>;
  /** POST /open/CreateAutoPEEvaluateDimension */
  CreateAutoPEEvaluateDimension(
    req: task.CreateAutoPEEvaluateDimensionReq,
  ): Promise<task.CreateAutoPEEvaluateDimensionResp>;
  /** POST /open/Completion */
  Completion(req: prompt.CompletionReq): Promise<Array<prompt.CompletionEventResp>>;
  /**
   * POST /open/CreateAutoPEPromptVersion
   *
   * PromptVersion info
   */
  CreateAutoPEPromptVersion(req: prompt.CreateAutoPEPromptVersionReq): Promise<prompt.CreateAutoPEPromptVersionResp>;
  /** POST /open/DeleteAutoPEDataRecords */
  DeleteAutoPEDataRecords(req: dataset.DeleteAutoPEDataRecordsReq): Promise<dataset.DeleteAutoPEDataRecordsResp>;
  /**
   * POST /open/CreateAutoPEUserAgreementRecord
   *
   * User Info
   */
  CreateAutoPEUserAgreementRecord(
    req: user_info.CreateAutoPEUserAgreementRecord,
  ): Promise<user_info.CreateAutoPEUserAgreementRecordResp>;
  /** POST /open/GetAutoPEUserSignedAgreementInfos */
  GetAutoPEUserSignedAgreementInfos(
    req: user_info.GetAutoPEUserSignedAgreementInfosReq,
  ): Promise<user_info.GetAutoPEUserSignedAgreementInfosResp>;
  /** POST /open/GenerateAIEdition */
  GenerateAIEdition(req: prompt.GenerateAIEditionReq): Promise<Array<prompt.GenerateAIEditionEventResp>>;
  /** POST /open/SaveFeedback */
  SaveFeedback(req: prompt.SaveFeedbackReq): Promise<prompt.SaveFeedbackResp>;
  /** POST /open/GenerateAutoPEEvaluateDimension */
  GenerateAutoPEEvaluateDimension(
    req: task.GenerateAutoPEEvaluateDimensionRequest,
  ): Promise<task.GenerateAutoPEEvaluateDimensionResponse>;
  /** POST /open/GetRandomCachedPrompt */
  GetRandomCachedPrompt(req: schema.Empty): Promise<prompt.GetRandomCachedPromptResp>;
  /** POST /open/GetMoreModelAnswer */
  GetMoreModelAnswer(req: prompt.GetMoreModelAnswerReq): Promise<prompt.GetMoreModelAnswerResp>;
  /** POST /open/GenerateMoreModelAnswer */
  GenerateMoreModelAnswer(req: prompt.GenerateMoreModelAnswerReq): Promise<prompt.GenerateMoreModelAnswerResp>;
  /** POST /open/GetAutoPETaskIntentions */
  GetAutoPETaskIntentions(req: prompt.GetAutoPETaskIntentionsReq): Promise<prompt.GetAutoPETaskIntentionsResp>;
  /** POST /open/GenerateIdealAnswer */
  GenerateIdealAnswer(req: prompt.GenerateIdealAnswerReq): Promise<Array<prompt.GenerateIdealAnswerEventResp>>;
  /** POST /open/DeleteAutoPETaskIntentions */
  DeleteAutoPETaskIntentions(req: prompt.DeleteAutoPETaskIntentionsReq): Promise<prompt.DeleteAutoPETaskIntentionsResp>;
  /** POST /open/CreateAutoPETaskIntentions */
  CreateAutoPETaskIntentions(req: prompt.CreateAutoPETaskIntentionsReq): Promise<prompt.CreateAutoPETaskIntentionsResp>;
  /** POST /open/GetAutoPETaskTokenConsumption */
  GetAutoPETaskTokenConsumption(
    req: task.GetAutoPETaskTokenConsumptionReq,
  ): Promise<task.GetAutoPETaskTokenConsumptionResp>;
  /** POST /open/UpdateAutoPEDialogRecord */
  UpdateAutoPEDialogRecord(req: dialog.UpdateAutoPEDialogRecordReq): Promise<dialog.UpdateAutoPEDialogRecordResp>;
  /** POST /open/DeleteAutoPEDialogRecord */
  DeleteAutoPEDialogRecord(req: dialog.DeleteAutoPEDialogRecordReq): Promise<dialog.DeleteAutoPEDialogRecordResp>;
  /** POST /open/CreateAutoPEDialogRecord */
  CreateAutoPEDialogRecord(req: dialog.CreateAutoPEDialogRecordReq): Promise<dialog.CreateAutoPEDialogRecordResp>;
  /** POST /open/GetAutoPEDialogRecord */
  GetAutoPEDialogRecord(req: dialog.GetAutoPEDialogRecordReq): Promise<dialog.GetAutoPEDialogRecordResp>;
  /** POST /open/ListAutoPEDialogRecords */
  ListAutoPEDialogRecords(req: dialog.ListAutoPEDialogRecordsReq): Promise<dialog.ListAutoPEDialogRecordsResp>;
  /**
   * POST /open/GetAutoPEDialogExamples
   *
   * Dialog
   */
  GetAutoPEDialogExamples(req: schema.Empty): Promise<dialog.GetAutoPEDialogExamplesResp>;
  /** POST /open/BatchCreateAutoPEDialogRecords */
  BatchCreateAutoPEDialogRecords(
    req: dialog.BatchCreateAutoPEDialogRecordsReq,
  ): Promise<dialog.BatchCreateAutoPEDialogRecordsResp>;
  /** POST /open/GenerateTunedPromptFromFeedback */
  GenerateTunedPromptFromFeedback(
    req: dialog.GenerateTunedPromptFromFeedbackReq,
  ): Promise<Array<dialog.GenerateTunedPromptFromFeedbackEventResp>>;
  /** POST /open/GenerateTunedPromptFromGSBFeedback */
  GenerateTunedPromptFromGSBFeedback(
    req: prompt.GenerateTunedPromptFromGSBFeedbackReq,
  ): Promise<Array<prompt.GenerateTunedPromptFromGSBFeedbackResp>>;
  /** POST /open/GetAutoPETask */
  GetAutoPETask(req: task.GetAutoPETaskReq): Promise<task.GetAutoPETaskResp>;
  /** POST /open/RunAgentOnlineOptimize */
  RunAgentOnlineOptimize(req: optimization.RunAgentOnlineOptimizeReq): Promise<optimization.RunAgentOnlineOptimizeResp>;
  /**
   * POST /open/CreateAutoPEAgentDataRecord
   *
   * agent optimize
   */
  CreateAutoPEAgentDataRecord(
    req: dataset.CreateAutoPEAgentDataRecordReq,
  ): Promise<dataset.CreateAutoPEAgentDataRecordResp>;
  /** POST /open/UpdateAutoPEAgentPromptTemplate */
  UpdateAutoPEAgentPromptTemplate(
    req: prompt.UpdateAutoPEAgentPromptTemplateReq,
  ): Promise<prompt.UpdateAutoPEAgentPromptTemplateResp>;
  /** POST /open/GetRunAgentOnlineOptimizeResult */
  GetRunAgentOnlineOptimizeResult(
    req: optimization.GetRunAgentOnlineOptimizeResultReq,
  ): Promise<optimization.GetRunAgentOnlineOptimizeResultResp>;
}

export type Await<T> = T extends Promise<infer R> ? R : T;
export type AutopeServiceApis = keyof IAutopeService;
export type AutopeServiceApiRequest<T extends AutopeServiceApis> = Parameters<IAutopeService[T]>[0];
export type AutopeServiceApiResponse<T extends AutopeServiceApis> = Await<ReturnType<IAutopeService[T]>>;
/* eslint-enable */
