// Copyright (c) 2025 Bytedance Ltd. and/or its affiliates
// Licensed under the 【火山方舟】原型应用软件自用许可协议
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at 
//     https://www.volcengine.com/docs/82379/1433703
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

import * as schema from './schema';

export enum ReocrdListFilter {
  /** Filter for good records */
  LIST_SCORE_BETTER = 1,
  /** Filter for same records */
  LIST_SCORE_SAME = 2,
  /** Filter for bad records */
  LIST_SCORE_BAD = 3,
}

export enum VoteType {
  /** Up vote */
  UP = 1,
  /** Down vote */
  DOWN = 2,
  /** No vote */
  NONE = 3,
}

export interface BatchCreateAutoPEDialogRecordsReq {
  /** The task that this dialog belongs to. */
  TaskId: string;
  /** The prompt version id that need to storage. */
  PromptVersionId: string;
  /** The dialogs. */
  Dialogs: Array<DialogRecord>;
}

export interface BatchCreateAutoPEDialogRecordsResp {
  /** The result of creating dialog record */
  Result: BatchCreateAutoPEDialogRecordsResult;
  /** The response metadata */
  ResponseMetadata: schema.ResponseMetadata;
}

export interface BatchCreateAutoPEDialogRecordsResult {
  /** The task that this dialog belongs to. */
  TaskId: string;
  /** The ids of the dialogs. */
  DialogIds: Array<string>;
}

export interface CreateAutoPEDialogRecordReq {
  /** The task that this dialog belongs to. */
  TaskId: string;
  /** The prompt version id that need to storage. */
  PromptVersionId: string;
  /** The messages of the dialog. */
  Messages: Array<Message>;
  /** The feedbacks of the dialog. */
  Feedbacks?: Array<DialogFeedback>;
  /** The score of the dialog. */
  Score?: number;
  /** The attributes of the dialog. */
  Attributes?: Array<string>;
}

export interface CreateAutoPEDialogRecordResp {
  /** The result of creating dialog record */
  Result: CreateAutoPEDialogRecordResult;
  /** The response metadata */
  ResponseMetadata: schema.ResponseMetadata;
}

export interface CreateAutoPEDialogRecordResult {
  /** The task that this dialog belongs to. */
  TaskId: string;
  /** The id of the dialog. */
  DialogId: string;
}

export interface DeleteAutoPEDialogRecordReq {
  /** The id of the task */
  TaskId: string;
  /** The ids of the dialogs */
  DialogIds: Array<string>;
  /** The id of the prompt version */
  PromptVersionId: string;
}

export interface DeleteAutoPEDialogRecordResp {
  /** The result of deleting dialog record */
  Result: schema.Empty;
  /** The response metadata */
  ResponseMetadata: schema.ResponseMetadata;
}

export interface DialogFeedback {
  /** The index of the message that need to feedback */
  MessageIndex: number;
  /** The index of the sub message that need to feedback, default is the 0 index in a content */
  MessageContentIndex?: number;
  /** The start index of the feedback */
  StartIndex: number;
  /** The end index of the feedback */
  EndIndex: number;
  /** The feedback of the message */
  Feedback?: string;
  /** The vote of the feedback */
  VoteType?: VoteType;
  /** The id of the feedback */
  FeedbackId: string;
}

export interface DialogRecord {
  /** The id of the dialog. */
  DialogId?: string;
  /** The messages of the dialog. */
  Messages: Array<Message>;
  /** The feedbacks of the dialog. */
  Feedbacks?: Array<DialogFeedback>;
  /** The score of the dialog. */
  Score?: number;
  /** The analysis of the evaluation score */
  Analysis?: string;
  /** Is AI evaluate score */
  IsAIEvaluateScore?: boolean;
  /** The attributes of the dialog. */
  Attributes?: Array<string>;
  /** The reference messages of the dialog. */
  ReferenceDialogMessages?: Array<Message>;
}

export interface GenerateTunedPromptFromFeedbackEventResp {
  /** Stream event name */
  event: string;
  /** Stream event data */
  data: string;
}

export interface GenerateTunedPromptFromFeedbackReq {
  /** The task that this dialog belongs to. */
  TaskId: string;
  /** The prompt version id that need to storage. */
  PromptVersionId: string;
  /** The feedback of the dialog. */
  Feedback?: DialogFeedback;
}

export interface GetAutoPEDialogExamplesResp {
  /** The result of getting dialog record */
  Result: Array<GetAutoPEDialogExamplesResult>;
  /** The response metadata */
  ResponseMetadata: schema.ResponseMetadata;
}

export interface GetAutoPEDialogExamplesResult {
  /** The title of the examples */
  Title: string;
  /** The messages of the dialog. */
  Messages: Array<Message>;
}

export interface GetAutoPEDialogRecordReq {
  /** The id of the task */
  TaskId: string;
  /** The id of the dialog */
  DialogId: string;
}

export interface GetAutoPEDialogRecordResp {
  /** The result of getting dialog record */
  Result: GetAutoPEDialogRecordResult;
  /** The response metadata */
  ResponseMetadata: schema.ResponseMetadata;
}

export interface GetAutoPEDialogRecordResult {
  /** The task that this dialog belongs to. */
  TaskId: string;
  /** The prompt version id that need to storage. */
  PromptVersionId: string;
  /** The dialogs, [0] means the base dialog, [1] means the compare dialog */
  Records: Array<DialogRecord>;
  /** The state of the data */
  DataState?: schema.JobState;
  /** Creation timestamp */
  CreateTime: string;
  /** Update timestamp */
  UpdateTime: string;
}

export interface ListAutoPEDialogRecordsReq {
  /** The id of the task */
  TaskId: string;
  /** The ids of the prompt versions, [0] means the base prompt version, [1] means the compare prompt version */
  PromptVersionIds: Array<string>;
  /** The ids of the dialogs */
  DialogIds?: Array<string>;
  /** The filter of the dialogs */
  Filter?: ListDialogFilter;
  /** The limit of the dialogs */
  Limit?: number;
  /** The offset of the dialogs */
  Offset?: number;
}

export interface ListAutoPEDialogRecordsResp {
  /** The result of listing dialog records */
  Result: ListAutoPEDialogRecordsResult;
  /** The response metadata */
  ResponseMetadata: schema.ResponseMetadata;
}

export interface ListAutoPEDialogRecordsResult {
  /** The dialogs */
  Dialogs: Array<GetAutoPEDialogRecordResult>;
  /** The total number of dialogs */
  Total: number;
  /** Total number of records that have user score */
  UserScoredTotal: number;
  /** Total number of records that have feedback */
  FeedbackTotal: number;
}

export interface ListDialogFilter {
  /** The attributes of the dialog */
  Attributes?: Array<string>;
  /** filter the list that compare version is better than base version */
  RuleFilter?: ReocrdListFilter;
  /** filter for the job state */
  JobState?: schema.JobState;
  /** filter for the data record ids */
  DataRecordIds?: Array<string>;
}

/** Define the struct for Message */
export interface Message {
  /** Role of the message ("user" or "assistant") */
  Role: string;
  /** List of content blocks for each message */
  Content: Array<MessageContent>;
}

/** Define the struct for MessageContent */
export interface MessageContent {
  /** Type of the message content ("text" or "image") */
  Type: string;
  /** Text content (if type is "text") */
  Text?: string;
}

export interface UpdateAutoPEDialogRecordReq {
  /** The task that this dialog belongs to. */
  TaskId: string;
  /** The prompt version id that need to storage. */
  PromptVersionId: string;
  /** The id of the dialog. */
  DialogId: string;
  /** The messages of the dialog. */
  Messages?: Array<Message>;
  /** The feedbacks of the dialog. */
  Feedbacks?: Array<DialogFeedback>;
  /** The score of the dialog. */
  Score?: number;
  /** The attributes of the dialog. */
  Attributes?: Array<string>;
  /** The analysis of the evaluation score */
  Analysis?: string;
  /** The index of the message that been modified */
  ModifyMessageIdx?: number;
}

export interface UpdateAutoPEDialogRecordResp {
  /** The result of updating dialog record */
  Result: schema.Empty;
  /** The response metadata */
  ResponseMetadata: schema.ResponseMetadata;
}
/* eslint-enable */
