// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

import * as schema from './schema';

/** Default prompt settings for a model */
export interface DefaultPromptSettings {
  /** The name of the model (e.g., "doubao-pro-32k") */
  ModelName: string;
  /** System prompt text (can be empty) */
  SystemPrompt?: string;
  /** Sampling temperature */
  Temperature: number;
  /** Default top_p */
  TopP: number;
}

export interface ListAvailableModelsResp {
  /** List of available models */
  Result?: ListAvailableModelsResult;
  /** Metadata for the response */
  ResponseMetadata?: schema.ResponseMetadata;
}

/** Result for listing available models */
export interface ListAvailableModelsResult {
  /** Default prompt settings */
  DefaultPromptSettings: DefaultPromptSettings;
  /** List of available models */
  SystemPresetModels: Array<ModelInfo>;
  /** List of custom models */
  CustomModels?: Array<ModelInfo>;
}

/** Model details structure */
export interface ModelInfo {
  /** The name of the model */
  ModelName: string;
  /** The endpoint for the model, now using ep-xxx */
  EndpointId: string;
  /** Whether the model supports images */
  SupportsImages: boolean;
  /** Maximum number of tokens the model can handle */
  MaxTokens: number;
  /** Token limit where a warning is triggered */
  WarningTokens: number;
  /** Whether this is the default model */
  Default: boolean;
  /** The name of the foundation model */
  FoundationModelName?: string;
}

export interface ModelSpec {
  /** Model name, e.g., "doubao-1.5-pro-32k-250115" */
  ModelName?: string;
  /** float top_p for the */
  TopP?: number;
  /** Temperature for sampling, e.g., 0.0 */
  Temperature?: number;
}
/* eslint-enable */
