// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

import * as schema from './schema';
import * as dataset from './dataset';

export interface CancelOptimizeReq {
  /** The id of the task that need to cancel */
  TaskId: string;
  /** The id of the prompt version that need to be optimized. */
  PromptVersionId: string;
}

export interface CancelOptimizeResp {
  /** Result of the optimization */
  Result?: schema.Empty;
  /** Metadata for the response */
  ResponseMetadata?: schema.ResponseMetadata;
}

export interface CompareOptimizationResultReq {
  /** The id of the task that need to compare */
  TaskId: string;
  /** Base prompt version ID */
  BasePromptVersionId: string;
  /** Compare prompt version ID */
  ComparePromptVersionId: string;
}

export interface CompareOptimizationResultResp {
  /** Result of the comparison */
  Result: CompareOptmizationResult;
  /** Metadata for the response */
  ResponseMetadata?: schema.ResponseMetadata;
}

export interface CompareOptmizationResult {
  /** Number of good cases */
  GoodCaseNumber: number;
  /** Number of same cases */
  SameCaseNumber: number;
  /** Number of bad cases */
  BadCaseNumber: number;
  /** Compare records */
  CompareRecords: Array<CompareRecords>;
}

export interface CompareRecords {
  /** Score of the record, GSB 模式下1: bad, 2: same, 3: good */
  Score: number;
  /** Number of records in the base prompt version */
  BasePromptVersionRecordsNum: string;
  /** Number of records in the compare prompt version */
  ComparePromptVersionRecordsNum: string;
}

export interface GetRunAgentOnlineOptimizeResultReq {
  /** The project name */
  ProjectName: string;
  /** The account id */
  TenantAccountId?: string;
  /** The user id */
  TenantUserId?: string;
}

export interface GetRunAgentOnlineOptimizeResultResp {
  /** Result of the optimization */
  Result: GetRunAgentOnlineOptimizeStatusResult;
  /** Metadata for the response */
  ResponseMetadata?: schema.ResponseMetadata;
}

export interface GetRunAgentOnlineOptimizeStatusResult {
  /** the list of prompt template, ordered by the workflow step index */
  PromptTemplateList: Array<PromptTemplate>;
  /** The state of all the jobs in workflow, after all prompt template optimized, then the job state is the success state */
  JobState: Array<schema.JobState>;
  /** The agent data records */
  AgentDataRecords: Array<dataset.AutoPEAgentDataRecord>;
  /** The total number of data records */
  AgentDataRecordTotal: number;
  /** The total number of data records required */
  AgentDataRecordRequiredTotal: number;
}

export interface PromptTemplate {
  /** The list of prompt template */
  PromptTemplate: string;
  /** The step index in the workflow */
  StepIndex: number;
}

export interface RunAgentOnlineOptimizeReq {
  /** The project name */
  ProjectName: string;
}

export interface RunAgentOnlineOptimizeResp {
  /** Result of the optimization */
  Result?: RunAgentOnlineOptimizeResult;
  /** Metadata for the response */
  ResponseMetadata?: schema.ResponseMetadata;
}

export interface RunAgentOnlineOptimizeResult {}

export interface RunOptimizeReq {
  /** The id of the task that need to create */
  TaskId: string;
  /** The id of the prompt version that need to be optimized. */
  PromptVersionId: string;
  /** Whether to optimize the evaluation dimension */
  OptimizeEvaluateDimension?: boolean;
  /** Stop configuration */
  StopConfig?: schema.OptimizeStopConfig;
  /** The rate of the optimize mode, 0 means effect first, 1 means cost-efficient first */
  OptimizeModeRate?: number;
}

export interface RunOptimizeResp {
  /** Result of the optimization */
  Result?: schema.Empty;
  /** Metadata for the response */
  ResponseMetadata?: schema.ResponseMetadata;
}
/* eslint-enable */
