// Copyright (c) 2025 Bytedance Ltd. and/or its affiliates
// Licensed under the 【火山方舟】原型应用软件自用许可协议
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at 
//     https://www.volcengine.com/docs/82379/1433703
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

import * as model from './model';
import * as schema from './schema';
import * as dataset from './dataset';
import * as dialog from './dialog';

export enum PromptVersionFilterType {
  /** Filter for all prompt versions */
  ALL = 1,
  /** Filter for prompt versions created by optimization */
  CREATED_BY_OPTIMIZATION = 2,
  /** Filter for prompt versions created manually */
  CREATED_BY_MANUAL = 3,
}

/** Define the struct for CompletionEventResp */
export interface CompletionEventResp {
  /** Event name */
  event: string;
  /** Event data */
  data: string;
}

export interface CompletionReq {
  /** Task id for auth */
  TaskId: string;
  /** Name of the model */
  ModelName: string;
  /** Prompt version id */
  PromptVersionId: string;
  /** List of variables */
  Variables?: Array<string>;
  /** Temperature for sampling */
  Temperature: number;
  /** TopP value for sampling */
  TopP: number;
  /** List of messages with roles and content */
  Messages: Array<Message>;
  /** Whether the completion is for a dialog */
  CompletingDialog?: boolean;
}

export interface CreateAutoPEPromptVersionReq {
  /** ID of the task */
  TaskId: string;
  /** Name of the model */
  ModelName: string;
  /** ID of the prompt version */
  BasePromptVersionId?: string;
  /** Version name, will auto increment by 1 */
  Version?: string;
  /** List of variables */
  Variables: Array<string>;
  /** TopP value */
  TopP: number;
  /** Temperature value */
  Temperature: number;
  /** List of messages with roles and content */
  Messages: Array<Message>;
  /** System prompt */
  SystemPrompt?: string;
  /** Evaluation dimension */
  EvaluationDimension?: string;
  /** Model Spec for the model answer */
  RefAnswerModelSpec?: model.ModelSpec;
  /** List of reference messages */
  ReferenceDialogMessages?: Array<Message>;
}

export interface CreateAutoPEPromptVersionResp {
  /** Result of creating the prompt version */
  Result: GetAutoPEPromptVersionResult;
  /** Metadata for the response */
  ResponseMetadata: schema.ResponseMetadata;
}

export interface CreateAutoPETaskIntentionsReq {
  /** Task id for auth */
  TaskId: string;
  /** List of variables */
  VariablesValues: Array<VariableValue>;
}

export interface CreateAutoPETaskIntentionsResp {
  /** Result of the response */
  Result: schema.Empty;
  /** Metadata for the response */
  ResponseMetadata: schema.ResponseMetadata;
}

export interface DeleteAutoPETaskIntentionsReq {
  /** Task id for auth */
  TaskId: string;
  /** List of intention ids */
  IntentionIds?: Array<string>;
}

export interface DeleteAutoPETaskIntentionsResp {
  /** Result of the response */
  Result: schema.Empty;
  /** Metadata for the response */
  ResponseMetadata: schema.ResponseMetadata;
}

export interface GenerateAIEditionEventResp {
  /** Event name */
  event: string;
  /** Event data */
  data: string;
}

export interface GenerateAIEditionReq {
  /** Task id for auth */
  TaskId?: string;
  /** Prompt Version id */
  PromptVersionId?: string;
  /** Data record id */
  DataRecordId?: string;
  /** Content feedback */
  ContentFeedBack: schema.ContentFeedBack;
  /** Model name */
  ModelName?: string;
  /** Temperature for sampling */
  Temperature?: number;
  /** TopP value for sampling */
  TopP?: number;
}

export interface GenerateIdealAnswerEventResp {
  /** Event name */
  event: string;
  /** Event data */
  data: string;
}

export interface GenerateIdealAnswerReq {
  /** Task id for auth */
  TaskId: string;
  /** Prompt version id */
  PromptVersionId: string;
  /** Name of the model */
  ModelName: string;
  /** Temperature for sampling */
  Temperature: number;
  /** List of variables */
  Variables: Array<string>;
  /** TopP value for sampling */
  TopP: number;
  /** Original Answer for the content */
  OriginAnswer: string;
  /** Feedback for the prompt */
  Feedback: string;
}

export interface GenerateMoreModelAnswerReq {
  /** Task id for auth */
  TaskId: string;
  /** Prompt version id */
  PromptVersionId: string;
  /** Name of the model */
  ModelName: string;
  /** Temperature for sampling */
  Temperature: number;
  /** TopP value for sampling */
  TopP: number;
  /** List of messages with roles and content */
  Messages: Array<Message>;
}

export interface GenerateMoreModelAnswerResp {
  /** Result of generating more model answers */
  Result: schema.Empty;
  /** Metadata for the response */
  ResponseMetadata: schema.ResponseMetadata;
}

/** Define the struct for GeneratePromptEventResp */
export interface GeneratePromptEventResp {
  /** Event name */
  event: string;
  /** Event data */
  data: string;
}

export interface GeneratePromptReq {
  /** Task id for auth */
  TaskId: string;
  /** Rule for generating the prompt */
  Rule: string;
  /** cloud resource projectname */
  ProjectName?: string;
  /** Model name */
  ModelName?: string;
  /** Temperature for sampling */
  Temperature?: number;
  /** TopP value for sampling */
  TopP?: number;
  /** Feedback for the prompt */
  Feedback?: string;
  /** Current prompt */
  CurrentPrompt?: string;
}

export interface GenerateTunedPromptFromGSBFeedbackReq {
  /** The task that this dialog belongs to. */
  TaskId: string;
  /** The prompt version id that need to storage. */
  PromptVersionId: string;
  /** The original model answer */
  ModelAnswer: string;
  /** The user answer */
  RefAnswer: string;
  /** The result for the comparation */
  GSBResult: dataset.RecordCompareRule;
  /** User analysis */
  UserAnalysis?: string;
}

export interface GenerateTunedPromptFromGSBFeedbackResp {
  /** Stream event name */
  event: string;
  /** Stream event data */
  data: string;
}

/** Define the struct for GenerateVariablesValuesEventResp */
export interface GenerateVariablesValuesEventResp {
  /** Event name */
  event: string;
  /** Event data */
  data: string;
}

export interface GenerateVariablesValuesReq {
  /** Task id for auth */
  TaskId: string;
  /** List of messages with roles and content */
  Messages: Array<Message>;
  /** Generation logic for the variables */
  GenerationLogic?: string;
  /** Prompt version id */
  PromptVersionId: string;
  /** Name of the model */
  ModelName?: string;
  /** Temperature for sampling */
  Temperature?: number;
  /** TopP value for sampling */
  TopP?: number;
  /** Use internet search for the variables generation */
  UseInternetSearch?: boolean;
}

export interface GetAutoPEPromptVersionReq {
  /** ID of the task */
  TaskId: string;
  /** ID of the version */
  VersionId?: string;
  /** If need the latest version */
  Latest?: boolean;
}

export interface GetAutoPEPromptVersionResp {
  /** Result of getting the prompt version */
  Result: GetAutoPEPromptVersionResult;
  /** Metadata for the response */
  ResponseMetadata: schema.ResponseMetadata;
}

/** Define the struct for GetPromptVersionResult */
export interface GetAutoPEPromptVersionResult {
  /** ID of the prompt version */
  Id?: string;
  /** Model name, e.g., "doubao-pro-32k" */
  ModelName?: string;
  /** List of variables, e.g., ["SOURCE_CODE", "SOURCE_LANGUAGE"] */
  Variables?: Array<string>;
  /** float top_p for the */
  TopP?: number;
  /** Temperature for sampling, e.g., 0.0 */
  Temperature?: number;
  /** System prompt (can be empty) */
  SystemPrompt?: string;
  /** Version name for the prompt, v1, v2, etc. */
  VersionName?: string;
  /** Average rating, could be null */
  AverageRating?: number;
  /** List of messages with roles and content */
  Messages?: Array<Message>;
  /** Evaluation dimension */
  EvaluationDimension?: string;
  /** Latest completion job id, used for filter records */
  LatestCompletionJobId?: string;
  /** Latest optimization job id, used for filter records */
  LatestOptimizationJobId?: string;
  /** Latest completion job state */
  LatestCompletionJobState?: schema.JobState;
  /** Latest optimization job state */
  LatestOptimizationJobState?: schema.JobState;
  /** Job error message */
  JobErrorMessage?: string;
  /** Dataset record count */
  DatasetRecordCount?: number;
  /** User score count */
  UserScoreCount?: number;
  /** Predecessor prompt version name */
  PredecessorPromptVersionName?: string;
  /** Create type */
  CreateType?: PromptVersionFilterType;
  /** Optimize evaluate dimension */
  OptimizeEvaluateDimension?: boolean;
  /** Task name */
  TaskName?: string;
  /** Job progress */
  JobProgress?: JobProgress;
  /** label to mark if need generate dimension */
  GenerateEvaluateDimension?: boolean;
  /** Evaluation dimension id */
  AIEvaluationDimension?: string;
  /** Stop configuration */
  StopConfig?: schema.OptimizeStopConfig;
  /** The rate of the optimize mode, 0 means effect first, 1 means cost-efficient first */
  OptimizeModeRate?: number;
  /** Use internet search for the variables generation */
  UseInternetSearch?: boolean;
  /** For multiround dialog purpose
List of dialog feedbacks */
  Feedbacks?: Array<dialog.DialogFeedback>;
  /** The type of the task, default is "DEFAULT", can be "DEFAULT", "DIALOG", "CLASSIFICATION", "OPEN_DOMAIN" */
  TaskType?: string;
  /** Vote type */
  VoteType?: dialog.VoteType;
  /** The score type, default is "POINTWISE", can be "POINTWISE", "PAIRWISE" */
  ScoreType?: string;
  /** Model Spec for the model answer */
  RefAnswerModelSpec?: model.ModelSpec;
  /** Creation timestamp */
  CreateTime?: string;
  /** Update timestamp */
  UpdateTime?: string;
}

export interface GetAutoPETaskIntentionsReq {
  /** Task id for auth */
  TaskId: string;
}

export interface GetAutoPETaskIntentionsResp {
  /** Result of the response */
  Result: GetAutoPETaskIntentionsResult;
  /** Metadata for the response */
  ResponseMetadata: schema.ResponseMetadata;
}

export interface GetAutoPETaskIntentionsResult {
  /** List of intentions */
  Intentions: Array<TaskIntention>;
}

export interface GetExamplePromptListResp {
  /** Result of the response */
  Result: Array<GetExamplePromptListResult>;
  /** Metadata for the response */
  ResponseMetadata: schema.ResponseMetadata;
}

/** Define the struct for GetExamplePromptListResult */
export interface GetExamplePromptListResult {
  /** Type of the result */
  Type: string;
  /** Label of the result */
  Label: string;
  /** Original prompt */
  OriginalPrompt: string;
}

export interface GetMoreModelAnswerReq {
  /** Task id for auth */
  TaskId: string;
  /** Prompt version id */
  PromptVersionId: string;
}

export interface GetMoreModelAnswerResp {
  /** Result of the response */
  Result: GetMoreModelAnswerResult;
  /** Metadata for the response */
  ResponseMetadata: schema.ResponseMetadata;
}

export interface GetMoreModelAnswerResult {
  /** List of model answers */
  ModelAnswers: Array<string>;
}

export interface GetRandomCachedPromptResp {
  /** Result of the response */
  Result: GetRandomCachedPromptResult;
  /** Metadata for the response */
  ResponseMetadata: schema.ResponseMetadata;
}

export interface GetRandomCachedPromptResult {
  /** Random cached prompt */
  Prompt: string;
}

export interface IntentionPair {
  /** Intention id */
  IntentionId: string;
  /** Intention */
  Intention: string;
}

/** Define the struct for the Job Progress */
export interface JobProgress {
  /** Job progress value */
  JobProgressValue: number;
  /** Optimal prompt */
  OptimalPrompt: string;
  /** Better count */
  BetterCount: number;
  /** Worse count */
  WorseCount: number;
  /** Total count */
  TotalCount: number;
  /** Initial full score count, GSB模式下为初始good评分数 */
  InitFullScoreCount: number;
  /** Full score count, GSB模式下为good评分数 */
  FullScoreCount: Array<number>;
  /** Initial average score */
  InitAverageScore: number;
  /** Average score */
  AverageScore: Array<number>;
  /** Full score increase ratio，GSB模式下为good评分增长比例 */
  FullScoreIncRatio: number;
  /** GSB same count */
  GSBSameDataCount: Array<number>;
  /** GSB same increase ratio */
  GSBSameIncRatio: number;
  /** GSB bad count */
  GSBBadDataCount: Array<number>;
  /** GSB bad increase ratio */
  GSBBadIncRatio: number;
  /** GSB rating increase count */
  GSBRatingIncCount: Array<number>;
  /** GSB rating decrease count */
  GSBRatingDecCount: Array<number>;
  /** Average score increase ratio */
  AverageScoreIncRatio: number;
  /** 对应"智能优化Prompt" */
  OptimizeTokenConsumption: number;
}

export interface ListAutoPEPromptVersionReq {
  /** ID of the task */
  TaskId: string;
  /** ID of the compared baseline prompt version */
  BaselinePromptVersionId?: string;
  /** Filter for the prompt versions, default is ALL, if indicate as CREATED_BY_OPTIMIZATION, will list the prompt versions created by optimization, need to indicate the BaselinePromptVersionId */
  Filter?: PromptVersionFilterType;
  /** label to mark if need find predecessor */
  FindPredecessor?: boolean;
}

export interface ListAutoPEPromptVersionResp {
  /** Result of listing prompt versions */
  Result: ListAutoPEPromptVersionResult;
  /** Metadata for the response */
  ResponseMetadata: schema.ResponseMetadata;
}

/** Define the struct for ListPromptVersionResult */
export interface ListAutoPEPromptVersionResult {
  /** Total number of prompt versions */
  Total: number;
  /** List of prompt versions */
  PromptVersionList: Array<GetAutoPEPromptVersionResult>;
}

/** Define the struct for Message */
export interface Message {
  /** Role of the message ("user" or "assistant") */
  Role: string;
  /** List of content blocks for each message */
  Content: Array<MessageContent>;
}

/** Define the struct for MessageContent */
export interface MessageContent {
  /** Type of the message content ("text" or "image") */
  Type: string;
  /** Text content (if type is "text") */
  Text?: string;
}

export interface SaveFeedbackReq {
  /** Task id for auth */
  TaskId: string;
  /** Prompt Version id */
  PromptVersionId?: string;
  /** Data record id */
  DataRecordId?: string;
  /** Content feedbacks */
  ContentFeedbacks: Array<schema.ContentFeedBack>;
}

export interface SaveFeedbackResp {
  /** Result of saving the feedback */
  Result: schema.Empty;
  /** Metadata for the response */
  ResponseMetadata: schema.ResponseMetadata;
}

export interface TaskIntention {
  /** Feedback id */
  FeedbackId: string;
  /** Feedback */
  Feedback: string;
  /** List of intentions */
  ListOfIntentions: Array<IntentionPair>;
}

export interface UpdateAutoPEAgentPromptTemplateReq {
  /** The id of the project */
  AutoPEProjectId: string;
  /** The step index in the workflow */
  StepIndex?: number;
}

export interface UpdateAutoPEAgentPromptTemplateResp {
  /** Result of the response */
  Result: schema.Empty;
  /** Metadata for the response */
  ResponseMetadata: schema.ResponseMetadata;
}

export interface UpdateAutoPEPromptVersionReq {
  /** ID of the task */
  TaskId: string;
  /** ID of the prompt version */
  PromptVersionId: string;
  /** List of messages with roles and content */
  Messages: Array<Message>;
  /** List of variables */
  Variables?: Array<string>;
  /** Name of the model */
  ModelName?: string;
  /** TopP value */
  TopP?: number;
  /** Temperature value */
  Temperature?: number;
  /** Evaluation dimension */
  EvaluationDimension?: string;
  /** label to mark if need generate dimension */
  GenerateEvaluateDimension?: boolean;
  /** List of dialog feedbacks */
  Feedbacks?: Array<dialog.DialogFeedback>;
  /** Vote type */
  VoteType?: dialog.VoteType;
  /** Modify the message by index */
  ModifyMessageIdx?: number;
  /** Model Spec for the model answer */
  RefAnswerModelSpec?: model.ModelSpec;
  /** List of reference messages */
  ReferenceDialogMessages?: Array<Message>;
}

export interface UpdateAutoPEPromptVersionResp {
  /** Result of updating the prompt version */
  Result: GetAutoPEPromptVersionResult;
  /** Metadata for the response */
  ResponseMetadata: schema.ResponseMetadata;
}

export interface VariableValue {
  /** name of the variable */
  Name: string;
  /** value of the variable */
  Value: string;
}
/* eslint-enable */
