// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

export enum AgentType {
  /** default */
  DEFAULT = 0,
  /** deep research */
  DEEP_RESEARCH = 1,
}

export enum ContentType {
  /** prompt */
  PROMPT = 1,
  /** ideal answer */
  IDEAL_ANSWER = 2,
  /** evaluate dimension */
  EVALUATE_DIMENSION = 3,
  /** user prompt */
  USER_PROMPT = 4,
  /** workflow */
  WORKFLOW = 5,
}

export enum JobState {
  /** job created */
  CREATED = 1,
  /** optimize job metric ready */
  METRIC_READY = 2,
  /** optimize job running */
  OPTIMIZING = 3,
  /** completion job running */
  COMPLETING = 4,
  /** evaluation job running */
  EVALUATING = 5,
  /** cold start generating */
  COLD_START_GENERATING = 6,
  /** optimize job finished */
  OPTIMIZE_SUCCESS = 7,
  /** completion job finished */
  COMPLETION_SUCCESS = 8,
  /** evaluation job finished */
  EVALUATION_SUCCESS = 9,
  /** cold start generate success */
  COLD_START_GENERATE_SUCCESS = 10,
  /** optimize job cancelled */
  OPTIMIZE_CANCELLED = 11,
  /** completion job cancelled */
  COMPLETION_CANCELLED = 12,
  /** evaluation job cancelled */
  EVALUATION_CANCELLED = 13,
  /** cold start generate cancelled */
  COLD_START_GENERATE_CANCELLED = 14,
  /** job creation error */
  CREATE_FAILED = 15,
  /** optimize job metric (Stage 1) error */
  METRIC_FAILED = 16,
  /** optimize job (Stage 2) error */
  OPTIMIZE_FAILED = 17,
  /** completion job error */
  COMPLETION_FAILED = 18,
  /** evaluation job error */
  EVALUATION_FAILED = 19,
  /** cold start generate failed */
  COLD_START_GENERATE_FAILED = 20,
  /** optimize job cancelling */
  OPTIMIZE_CANCELLING = 21,
  /** optimize job stopped without result */
  OPTIMIZE_CANCELLED_WITHOUT_RESULT = 22,
}

export enum VoteType {
  /** Up vote */
  UP = 1,
  /** Down vote */
  DOWN = 2,
  /** No vote */
  NONE = 3,
}

export interface ContentFeedBack {
  /** 类型： PROMPT, IDEAL_ANSWER, EVALUATE_DIMENSION, USER_PROMPT, WORKFLOW */
  Type: ContentType;
  /** Feedback for the prompt */
  Feedback?: string;
  /** start string index of the content */
  StartIdx?: number;
  /** end string index of the content */
  EndIdx?: number;
  /** full original content */
  FullOriginalContent?: string;
  /** vote type */
  VoteType?: VoteType;
}

export interface Empty {}

export interface ErrData {
  Code: string;
  CodeN: number;
  Message: string;
}

export interface OptimizeStopConfig {
  /** Whether to enable custom stop */
  EnableCustomStop?: boolean;
  /** Stop by kilo tokens */
  MaxKiloTokens?: number;
  /** Stop by minutes */
  MaxMinutes?: number;
}

export interface ResponseMetadata {
  RequestId: string;
  Action: string;
  Version: string;
  Service: string;
  Region: string;
  Error?: ErrData;
}
/* eslint-enable */
