// Copyright (c) 2025 Bytedance Ltd. and/or its affiliates
// Licensed under the 【火山方舟】原型应用软件自用许可协议
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at 
//     https://www.volcengine.com/docs/82379/1433703
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

import * as schema from './schema';

export interface CreateAutoPEEvaluateDimensionReq {
  /** The task that this evaluate dimension belongs to. */
  TaskId: string;
  /** The prompt version id that need to storage. */
  PromptVersionId: string;
  /** The content of the evaluate dimension. */
  Content: string;
}

export interface CreateAutoPEEvaluateDimensionResp {
  /** The result of listing tasks */
  Result: CreateAutoPEEvaluateDimensionResult;
  /** The response metadata */
  ResponseMetadata: schema.ResponseMetadata;
}

export interface CreateAutoPEEvaluateDimensionResult {
  /** The task that this evaluate dimension belongs to. */
  TaskId: string;
  /** The history of the evaluate dimension. */
  EvaluationDimensionHistory: Array<EvaluateDimension>;
  /** The reminder of the reference answer. */
  ReferenceAnswerReminder?: string;
}

export interface CreateAutoPETaskReq {
  /** The name of the task */
  TaskName?: string;
  /** The type of the task, default is "DEFAULT", can be "DEFAULT", "DIALOG", "CLASSIFICATION", "OPEN_DOMAIN" */
  TaskType?: string;
  /** The prompt of the task */
  Prompt: string;
  /** The target model */
  TargetModel?: string;
  /** The temperature */
  Temperature?: number;
  /** The top p value */
  TopP?: number;
  /** cloud resource projectname */
  ProjectName?: string;
  /** cloud resource tags */
  Tags?: Array<Tag>;
  /** The score type, default is "POINTWISE", can be "POINTWISE", "PAIRWISE" */
  ScoreType?: string;
  /** The agent type, default is "DEFAULT", can be "DEFAULT", "DEEP_RESEARCH" */
  FromAgent?: schema.AgentType;
}

export interface CreateAutoPETaskResp {
  /** The result of creating a task */
  Result: CreateAutoPETaskResult;
  /** The response metadata */
  ResponseMetadata: schema.ResponseMetadata;
}

export interface CreateAutoPETaskResult {
  /** The id of the created task */
  TaskId: string;
  /** The last version of the task */
  LastVersion: string;
  /** The prompt version id that need to storage. */
  PromptversionId: string;
}

export interface DeleteAutoPETaskReq {
  /** The id of the task */
  TaskId: string;
}

export interface DeleteAutoPETaskResp {
  /** The result of deleting a task */
  Result: DeleteAutoPETaskResult;
  /** The response metadata */
  ResponseMetadata: schema.ResponseMetadata;
}

export interface DeleteAutoPETaskResult {}

export interface EvaluateDimension {
  /** The Content of the evaluation dimension */
  Content?: string;
  /** The create time of the Evaluation */
  CreateTime?: string;
}

export interface GenerateAutoPEEvaluateDimensionRequest {
  /** Task ID */
  TaskId: string;
  /** Prompt version ID */
  PromptVersionId: string;
}

export interface GenerateAutoPEEvaluateDimensionResponse {
  /** Result of generating the evaluate dimension */
  Result?: GenerateAutoPEEvaluateDimensionResult;
  /** Metadata for the response */
  ResponseMetadata?: schema.ResponseMetadata;
}

export interface GenerateAutoPEEvaluateDimensionResult {}

export interface GetAutoPEEvaluateDimensionHistoryReq {
  /** The id of the task */
  TaskId: string;
}

export interface GetAutoPEEvaluateDimensionHistoryResp {
  /** The result of getting the history of the evaluate dimension */
  Result: GetAutoPEEvaluateDimensionHistoryResult;
  /** The response metadata */
  ResponseMetadata: schema.ResponseMetadata;
}

export interface GetAutoPEEvaluateDimensionHistoryResult {
  /** The id of the task */
  TaskId: string;
  /** The history of the evaluate dimension. */
  EvaluationDimensionHistory: Array<EvaluateDimension>;
}

export interface GetAutoPETaskReq {
  /** The id of the task */
  TaskId: string;
  /** cloud resource projectname */
  ProjectName?: string;
}

export interface GetAutoPETaskResp {
  /** The result of getting a task */
  Result: GetAutoPETaskResult;
  /** The response metadata */
  ResponseMetadata: schema.ResponseMetadata;
}

export interface GetAutoPETaskResult {
  /** The name of the task */
  TaskName: string;
  /** The id of the task */
  TaskId: string;
  /** The type of the task */
  TaskType: string;
  /** The last version of the task */
  LastVersion: string;
  /** The time when the task was created */
  CreateTime: string;
  /** The time when the task was updated */
  UpdateTime: string;
  /** The prompt of the task */
  Prompt: string;
  /** The user who created the task */
  UserName: string;
  /** The email of user who create the task */
  UserEmail: string;
  /** The latest job completion state */
  LatestJobCompletionState?: schema.JobState;
  /** The latest job optimization state */
  LatestJobOptimizationState?: schema.JobState;
  /** The history of the evaluate dimension. */
  EvaluationDimensionHistory?: Array<EvaluateDimension>;
  /** The tags of the task */
  Tags?: Array<Tag>;
  /** The score type, default is "POINTWISE", can be "POINTWISE", "PAIRWISE" */
  ScoreType?: string;
  /** The agent type, default is "DEFAULT", can be "DEFAULT", "DEEP_RESEARCH" */
  FromAgent?: schema.AgentType;
}

export interface GetAutoPETaskTokenConsumptionReq {
  /** The id of the task */
  TaskId: string;
}

export interface GetAutoPETaskTokenConsumptionResp {
  /** The result of getting the token consumption of the task */
  Result: GetAutoPETaskTokenConsumptionResult;
  /** The response metadata */
  ResponseMetadata: schema.ResponseMetadata;
}

export interface GetAutoPETaskTokenConsumptionResult {
  /** The token consumption of the task */
  TotalTokenConsumption: number;
}

export interface ListAutoPETasksFilter {
  /** The fuzzy match for name */
  Name?: string;
  /** The fuzzy match for prompt content. */
  SearchContent?: string;
  /** The time range to filter, example: {"start": "2021-01-01T00:00:00", "end": "2021-01-02T00:00:00"} */
  TimeRange?: TimeRange;
  /** The state to filter, */
  States?: Array<schema.JobState>;
  /** The task id to filter out the tasks in the same ape project */
  SameProjectWithTaskId?: string;
}

export interface ListAutoPETasksReq {
  /** The search content */
  Filter?: ListAutoPETasksFilter;
  /** The limit of the result */
  Limit?: number;
  /** The offset of the result */
  Offset?: number;
  /** The field to sort by, default is create_time, support create_time, update_time */
  SortBy?: string;
  /** cloud resource projectname */
  ProjectName?: string;
  /** cloud resorce tag filters */
  TagFilters?: Array<TagFilter>;
}

export interface ListAutoPETasksResp {
  /** The result of listing tasks */
  Result: ListAutoPETasksResult;
  /** The response metadata */
  ResponseMetadata: schema.ResponseMetadata;
}

export interface ListAutoPETasksResult {
  /** The list of tasks */
  Tasks: Array<GetAutoPETaskResult>;
  /** The total number of tasks */
  Total: number;
}

export interface Tag {
  Key: string;
  Value: string;
}

export interface TagFilter {
  Key: string;
  Values?: Array<string>;
}

export interface TimeRange {
  StartTime: string;
  EndTime: string;
}

export interface UpdataAutoPETaskResult {}

export interface UpdateAutoPETaskReq {
  /** The id of the task */
  TaskId: string;
  /** The name of the task */
  TaskName?: string;
  /** The prompt of the task */
  Prompt?: string;
  /** The last version of the task */
  LastVersion?: string;
}

export interface UpdateAutoPETaskResp {
  /** The result of updating a task */
  Result: UpdataAutoPETaskResult;
  /** The response metadata */
  ResponseMetadata: schema.ResponseMetadata;
}
/* eslint-enable */
