// Copyright (c) 2025 Bytedance Ltd. and/or its affiliates
// Licensed under the 【火山方舟】原型应用软件自用许可协议
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at 
//     https://www.volcengine.com/docs/82379/1433703
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

import * as schema from './schema';

export interface CreateAutoPEUserAgreementRecord {
  /** Project name */
  ProjectName?: string;
}

export interface CreateAutoPEUserAgreementRecordResp {
  /** Result of creating the user agreement record */
  Result: CreateAutoPEUserAgreementRecordResult;
  /** Metadata for the response */
  ResponseMetadata: schema.ResponseMetadata;
}

export interface CreateAutoPEUserAgreementRecordResult {
  /** Id of the user agreement record */
  UserRecordId: string;
  /** Creation timestamp */
  CreateTime: string;
}

export interface GetAutoPEUserSignedAgreementInfosReq {
  /** Project name */
  ProjectName?: string;
}

export interface GetAutoPEUserSignedAgreementInfosResp {
  /** Result of getting the user agreement record */
  Result: GetAutoPEUserSignedAgreementInfosResult;
  /** Metadata for the response */
  ResponseMetadata: schema.ResponseMetadata;
}

export interface GetAutoPEUserSignedAgreementInfosResult {
  /** Whether the user has signed the data usage agreement */
  SignedDataUsageAgreement: boolean;
}
/* eslint-enable */
