// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

import * as schema from './schema';

export interface CreateAutoPEUserAgreementRecord {
  /** Project name */
  ProjectName?: string;
}

export interface CreateAutoPEUserAgreementRecordResp {
  /** Result of creating the user agreement record */
  Result: CreateAutoPEUserAgreementRecordResult;
  /** Metadata for the response */
  ResponseMetadata: schema.ResponseMetadata;
}

export interface CreateAutoPEUserAgreementRecordResult {
  /** Id of the user agreement record */
  UserRecordId: string;
  /** Creation timestamp */
  CreateTime: string;
}

export interface GetAutoPEUserSignedAgreementInfosReq {
  /** Project name */
  ProjectName?: string;
}

export interface GetAutoPEUserSignedAgreementInfosResp {
  /** Result of getting the user agreement record */
  Result: GetAutoPEUserSignedAgreementInfosResult;
  /** Metadata for the response */
  ResponseMetadata: schema.ResponseMetadata;
}

export interface GetAutoPEUserSignedAgreementInfosResult {
  /** Whether the user has signed the data usage agreement */
  SignedDataUsageAgreement: boolean;
}
/* eslint-enable */
