app_id: "YOUR APP ID"
app_secret: "YOUR APP SECRET"
dest_folder_token: "YOUR WORKING FOLDER"
contact_list:
  - name: "Your name"
    id_type: "email"
    id: "your.email@gmail.com"
  - name: "Arkitect代码开发群"
    description: "将和arkitect代码仓库相关的信息发送到这个群"
    id_type: "chat_id"
    id: "oc_xxxxxxxxxx"
