"""Public structured cases for local installation smoke routing."""

CASE_SPECS = (
    {
        "case_id": "direct-identity",
        "category": "direct_skill",
        "goal": "resolve_identity",
        "chain": "single_operation",
        "objects": ["compound_identifier"],
        "operations": ["resolve_identity"],
        "roles": [],
        "candidates": ["resolve-chemical-identities"],
        "ambiguities": [],
        "unsupported": [],
        "route_type": "direct_skill",
        "target": "resolve-chemical-identities",
    },
    {
        "case_id": "direct-standardize",
        "category": "direct_skill",
        "goal": "standardize_structure",
        "chain": "single_operation",
        "objects": ["chemical_structure"],
        "operations": ["standardize_structure"],
        "roles": [],
        "candidates": ["standardize-chemical-structures"],
        "ambiguities": [],
        "unsupported": [],
        "route_type": "direct_skill",
        "target": "standardize-chemical-structures",
    },
    {
        "case_id": "chain-structure-features",
        "category": "direct_skill_chain",
        "goal": "compute_molecular_features",
        "chain": "explicit_bounded_chain",
        "objects": ["chemical_structure"],
        "operations": ["standardize_structure", "compute_fingerprint"],
        "roles": [],
        "candidates": ["structure-features-v1"],
        "ambiguities": [],
        "unsupported": [],
        "route_type": "direct_skill_chain",
        "target": "structure-features-v1",
    },
    {
        "case_id": "chain-reaction-precedent",
        "category": "direct_skill_chain",
        "goal": "search_reaction_precedent",
        "chain": "explicit_bounded_chain",
        "objects": ["reaction_record"],
        "operations": ["curate_reaction", "search_reaction_precedent"],
        "roles": [],
        "candidates": ["reaction-precedent-v1"],
        "ambiguities": [],
        "unsupported": [],
        "route_type": "direct_skill_chain",
        "target": "reaction-precedent-v1",
    },
    {
        "case_id": "workflow-compound-evidence",
        "category": "workflow",
        "goal": "build_compound_evidence",
        "chain": "complete_evidence_workflow",
        "objects": ["compound_identifier"],
        "operations": [
            "resolve_identity",
            "standardize_structure",
            "compute_fingerprint",
        ],
        "roles": [],
        "candidates": ["compound-evidence-v1"],
        "ambiguities": [],
        "unsupported": [],
        "route_type": "workflow_a",
        "target": "compound-evidence-v1",
    },
    {
        "case_id": "workflow-route-evidence",
        "category": "workflow",
        "goal": "build_route_evidence_review",
        "chain": "complete_evidence_workflow",
        "objects": ["reaction_record", "route_record"],
        "operations": [
            "curate_reaction",
            "search_reaction_precedent",
            "review_existing_routes",
        ],
        "roles": ["reaction_input", "route_input"],
        "candidates": ["route-evidence-review-v1"],
        "ambiguities": [],
        "unsupported": [],
        "route_type": "workflow_b",
        "target": "route-evidence-review-v1",
    },
    {
        "case_id": "clarify-missing-input",
        "category": "clarification",
        "goal": "compute_molecular_features",
        "chain": "unknown",
        "objects": ["chemical_structure"],
        "operations": [],
        "roles": [],
        "candidates": ["compute-molecular-features"],
        "ambiguities": ["missing_input_artifact"],
        "unsupported": [],
        "route_type": "clarification_required",
        "target": None,
    },
    {
        "case_id": "clarify-search-strategy",
        "category": "clarification",
        "goal": "search_or_curate_library",
        "chain": "unknown",
        "objects": ["compound_collection"],
        "operations": [],
        "roles": [],
        "candidates": [],
        "ambiguities": ["missing_search_strategy"],
        "unsupported": [],
        "route_type": "clarification_required",
        "target": None,
    },
    {
        "case_id": "unsupported-toxicity",
        "category": "unsupported",
        "goal": "unsupported_scientific_goal",
        "chain": "unknown",
        "objects": ["chemical_structure"],
        "operations": [],
        "roles": [],
        "candidates": [],
        "ambiguities": [],
        "unsupported": ["toxicity_prediction"],
        "route_type": "unsupported",
        "target": None,
    },
    {
        "case_id": "unsupported-structure-prediction",
        "category": "unsupported",
        "goal": "unsupported_scientific_goal",
        "chain": "unknown",
        "objects": ["chemical_structure"],
        "operations": [],
        "roles": [],
        "candidates": [],
        "ambiguities": [],
        "unsupported": ["structure_prediction"],
        "route_type": "unsupported",
        "target": None,
    },
    {
        "case_id": "negative-weather",
        "category": "non_chemistry_negative",
        "goal": "unclear_goal",
        "chain": "unknown",
        "objects": [],
        "operations": [],
        "roles": [],
        "candidates": [],
        "ambiguities": ["missing_research_object"],
        "unsupported": [],
        "route_type": "clarification_required",
        "target": None,
    },
    {
        "case_id": "negative-translation",
        "category": "non_chemistry_negative",
        "goal": "unclear_goal",
        "chain": "unknown",
        "objects": ["unknown_chemical_object"],
        "operations": [],
        "roles": [],
        "candidates": [],
        "ambiguities": ["ambiguous_direct_vs_workflow"],
        "unsupported": [],
        "route_type": "clarification_required",
        "target": None,
    },
)
